title: "Things I Find Interesting"
description: "Random explorations into hardware, software, and everything in between."
lang: en
url: "https://andrewdkennedy1.github.io"
author:
  name: "Andrew Kennedy"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
